TEQUILA_PLATFORM_VERSION = uno

TEQUILA_BUILD_DATE := $(shell date -u +%Y%m%d_%H%M%S)

# Filter out random types, so it'll reset to UNOFFICIAL
ifeq ($(filter RELEASE EXPERIMENTAL,$(TEQUILA_BUILDTYPE)),)
    TEQUILA_BUILDTYPE := UNOFFICIAL
endif

TEQUILA_VERSION_SUFFIX := $(TEQUILA_BUILD_DATE)-$(TEQUILA_BUILDTYPE)

# Internal version
TEQUILA_VERSION := $(TEQUILA_PLATFORM_VERSION)-$(TEQUILA_VERSION_SUFFIX)-$(TEQUILA_BUILD)

# Display version
TEQUILA_DISPLAY_VERSION := $(TEQUILA_PLATFORM_VERSION)-$(TEQUILA_VERSION_SUFFIX)
